// Seed records extracted from "GaileNald - Suppliers Catalog" CSV.
// Each record maps to the wedding_suppliers table.

const records = [
  {
    category: 'HMUA Bride',
    supplier_name: 'Makeup by Odessa',
    estimated_amount: 75000,
    actual_amount: 75000,
    total_paid: 65000,
    gaile_paid: 65000,
    nald_paid: 0,
    balance: 10000,
    first_payment: 'April 17, 2025',
    next_payment: 'March 7, 2027',
    payment_notes: 'March 14, 2026 (₱45,000) – paid March 15, 2026 | March 7, 2027 (₱10,000)',
    status: 'Booked DP Paid',
    contract_sent: 'Email',
    remarks: 'Option A (₱65,000): HMU for Bride only + ₱10,000 OOTF for Silang. Option B (₱90,000): HMU for Bride + 6 heads (second team of Odessa). ₱300/head/meal (BLD) = ₱900/head. Confirm final number of crews OTD.',
  },
  {
    category: 'Ceremony and Reception',
    supplier_name: 'Farm Hills Garden',
    estimated_amount: 439000,
    actual_amount: 439000,
    total_paid: 50000,
    gaile_paid: 25000,
    nald_paid: 25000,
    balance: 389000,
    first_payment: 'April 11, 2025',
    next_payment: 'Sep 14, 2026 / Dec 14, 2026 / Feb 14, 2027',
    payment_notes: '50-30-20 Scheme: 50% ₱194,500 (Sep 14, 2026) | 30% ₱116,700 (Dec 14, 2026) | 20% ₱77,800 (Feb 14, 2027)',
    status: 'Booked DP Paid',
    contract_sent: 'Email',
    remarks: 'All-in package for 2027 for 100 pax (+10 free). Includes venue, catering, lights & sounds, 3-layered cake, etc. Freebies: LED wall, coffee bar, host, photobooth, overnight stay for 4 pax. Choose 1 additional freebie: mobile bar.',
  },
  {
    category: 'Host',
    supplier_name: 'Angel Castro',
    estimated_amount: 10000,
    actual_amount: 10000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 10000,
    first_payment: 'March 14, 2027',
    next_payment: 'March 14, 2027',
    payment_notes: 'Additional ₱10,000 for 2027 event',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: 'FHG All In Package Freebie. Confirm final number of crews OTD.',
  },
  {
    category: 'Styling',
    supplier_name: 'LED Wall',
    estimated_amount: 0,
    actual_amount: 0,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 0,
    first_payment: '',
    next_payment: '',
    payment_notes: 'FHG All In Package Freebie',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: 'FHG All In Package Freebie',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Foodcart - Coffee Bar (Altitude Coffee)',
    estimated_amount: 0,
    actual_amount: 0,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 0,
    first_payment: '',
    next_payment: '',
    payment_notes: 'FHG All In Package Freebie',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: 'FHG Freebie. 75 cups. Coffee: Americano, Latte, Caramel Latte, Spanish Latte, White Mocha. Non-coffee: Dark Chocolate, Earl Grey Hot Tea.',
  },
  {
    category: 'Photographer',
    supplier_name: 'Photobooth - Parallel Blooms',
    estimated_amount: 20000,
    actual_amount: 18000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 18000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: '',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Foodcart - Mobile Bar - Tipsy Tavern (After Party)',
    estimated_amount: 15000,
    actual_amount: 15000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 15000,
    first_payment: 'November XX, 2026',
    next_payment: 'March 14, 2027',
    payment_notes: 'FHG Freebie. Nov XX, 2026: ₱7,500 upgrade to Signature Package. Mar 14, 2027: ₱7,500 remaining balance.',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: 'Upgrade to Signature Package: 2 Premium Cocktails (Lychee Margarita, Amaretto Sour), 2 Classic Cocktails (Mojito, Appletini), 25 cans of beer, 1 bottle of shots (Tequila). Confirm if pwede magbayad ng November.',
  },
  {
    category: 'Accommodation',
    supplier_name: 'FHG Overnight Stay for 4 pax',
    estimated_amount: 0,
    actual_amount: 0,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 0,
    first_payment: '',
    next_payment: '',
    payment_notes: 'FHG All In Package Freebie',
    status: 'Booked DP Paid',
    contract_sent: 'All in FHG',
    remarks: 'Rox, Sheena, Ivan, Ryan & Egay',
  },
  {
    category: 'Videographer',
    supplier_name: 'Our Story Films',
    estimated_amount: 130000,
    actual_amount: 135000,
    total_paid: 25000,
    gaile_paid: 5000,
    nald_paid: 20000,
    balance: 110000,
    first_payment: 'December 14, 2025',
    next_payment: 'April 27, 2026 / March 14, 2027',
    payment_notes: 'Apr 27, 2026: ₱15,000 (Nald) | Mar 14, 2027: ₱110,000 (pay remaining balance)',
    status: 'Booked DP Paid',
    contract_sent: 'Facebook',
    remarks: 'Sparks Package (₱130,000) + OOTF ₱5,000. ₱250/head/meal (BLD) = ₱750/head x 8 = ₱6,000.',
  },
  {
    category: 'Bride Outfit',
    supplier_name: 'Gown (@byannewong)',
    estimated_amount: 100000,
    actual_amount: 90000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 90000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Groom Outfit',
    supplier_name: 'Barong + Slacks (JRRM Embroidery / Denise Ong / Likha Nimo / Santi Obcena / GA Barong)',
    estimated_amount: 50000,
    actual_amount: 50000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 50000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'HMUA Entourage',
    supplier_name: 'Savvy Saviv (Makeup by Shielo)',
    estimated_amount: 20000,
    actual_amount: 16000,
    total_paid: 2000,
    gaile_paid: 2000,
    nald_paid: 0,
    balance: 14000,
    first_payment: 'March 2, 2026',
    next_payment: 'March 14, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'WaW Find. Final list by Oct. ₱200/head/meal (BL) = ₱400/head x 2 = ₱800.',
  },
  {
    category: 'HMUA Entourage',
    supplier_name: 'Glam Team of Makeup by Shy San Diego',
    estimated_amount: 17000,
    actual_amount: 17000,
    total_paid: 4000,
    gaile_paid: 4000,
    nald_paid: 0,
    balance: 13000,
    first_payment: 'June 10, 2026',
    next_payment: 'March 14, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: '',
  },
  {
    category: 'Singer',
    supplier_name: 'Jholo Cabero Music',
    estimated_amount: 23000,
    actual_amount: 23000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 23000,
    first_payment: '',
    next_payment: 'March 14, 2027',
    payment_notes: '',
    status: 'Booked DP Paid',
    contract_sent: 'Facebook',
    remarks: 'No downpayment required. May increase ₱20,000 rate by ₱3,000 for 2027-2028 events.',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Foodcart - Ay Sauce',
    estimated_amount: 10000,
    actual_amount: 11000,
    total_paid: 5500,
    gaile_paid: 0,
    nald_paid: 5500,
    balance: 5500,
    first_payment: 'March 22, 2026',
    next_payment: 'March 7, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: '',
    remarks: 'Pastries for cocktail hour, 75 pax: revel bar, cookies (original, matcha, red velvet), brownies, cheesecake bites, croissants.',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Foodcart - Potato Corner',
    estimated_amount: 10000,
    actual_amount: 15799,
    total_paid: 7899.50,
    gaile_paid: 7899.50,
    nald_paid: 0,
    balance: 7899.50,
    first_payment: 'March 16, 2026',
    next_payment: 'March 7, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: '',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Invitation Illustration by Ilili Why',
    estimated_amount: 3000,
    actual_amount: 2300,
    total_paid: 2300,
    gaile_paid: 2300,
    nald_paid: 0,
    balance: 0,
    first_payment: 'July 22, 2025',
    next_payment: '',
    payment_notes: 'One time payment',
    status: 'Fully Paid',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Coordinator',
    supplier_name: 'Events by Tam Ramos',
    estimated_amount: 52000,
    actual_amount: 52000,
    total_paid: 5000,
    gaile_paid: 5000,
    nald_paid: 0,
    balance: 47000,
    first_payment: 'May 18, 2025',
    next_payment: 'Feb 28, 2027 / March 14, 2027',
    payment_notes: 'Feb 28, 2027: ₱17,000 | Mar 14, 2027: ₱30,000',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: '₱300/head/meal (BLD) = ₱900/head x 7 = ₱6,300.',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Rings',
    estimated_amount: 100000,
    actual_amount: 110000,
    total_paid: 110000,
    gaile_paid: 55000,
    nald_paid: 55000,
    balance: 0,
    first_payment: 'March 22, 2026',
    next_payment: '',
    payment_notes: 'Fully paid: April 25, 2026',
    status: 'Fully Paid',
    contract_sent: '',
    remarks: 'Supplier: Tito Ronald Razo',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Essentials (Bible, Candle etc.) - gifties.metro',
    estimated_amount: 3000,
    actual_amount: 2970,
    total_paid: 2970,
    gaile_paid: 2970,
    nald_paid: 0,
    balance: 0,
    first_payment: 'May 4, 2026',
    next_payment: '',
    payment_notes: 'Pending payment upon Tiktok checkout for shipping fee',
    status: 'Fully Paid',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Foodcart - Fedici',
    estimated_amount: 35000,
    actual_amount: 32000,
    total_paid: 5000,
    gaile_paid: 0,
    nald_paid: 5000,
    balance: 27000,
    first_payment: 'February 28, 2026',
    next_payment: 'February 28, 2027',
    payment_notes: 'Feb 28, 2026: ₱5,000 | Feb 28, 2027: ₱27,000',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: '100 pax: Charcuterie Set, Mini Cheesecakes, Honey Lemonade Juice Station, Black Truffle Pasta Station, Dessert Station, Flower Bar, Ice Cream Station.',
  },
  {
    category: 'Accommodation',
    supplier_name: 'FHG Family Suite 1 (Bride Family Suite)',
    estimated_amount: 25000,
    actual_amount: 25000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 25000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Accommodation',
    supplier_name: 'FHG Family Suite 2 (Groom Family Suite)',
    estimated_amount: 25000,
    actual_amount: 25000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 25000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Bride Outfit',
    supplier_name: 'Shoes (Bride)',
    estimated_amount: 10000,
    actual_amount: 10000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 10000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Groom Outfit',
    supplier_name: 'Shoes (Groom)',
    estimated_amount: 10000,
    actual_amount: 10000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 10000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Gifts/Souvenirs',
    supplier_name: 'The Perfume Refilling Station',
    estimated_amount: 25000,
    actual_amount: 24249,
    total_paid: 5000,
    gaile_paid: 0,
    nald_paid: 5000,
    balance: 19249,
    first_payment: 'May 10, 2025',
    next_payment: 'February 12, 2027',
    payment_notes: 'February 12, 2027: ₱19,249',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: '30ml Chloe Perfumes for 100 pax, laser engraving, selfie mirror, LED. Transpo Allowance ₱1,500. Crew Meals ₱750.',
  },
  {
    category: 'Ceremony and Reception',
    supplier_name: 'After Party - Restaurant + Lights & Sounds',
    estimated_amount: 15000,
    actual_amount: 15000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 15000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '3 hrs (10pm–1am). No lights & sounds but can connect via mp3/bluetooth. Pavilion ₱13,000/hour.',
  },
  {
    category: 'Photographer',
    supplier_name: 'Aniya Photo',
    estimated_amount: 80000,
    actual_amount: 80000,
    total_paid: 40000,
    gaile_paid: 12000,
    nald_paid: 28000,
    balance: 40000,
    first_payment: 'August 1, 2025',
    next_payment: 'April 27, 2026 / March 14, 2027',
    payment_notes: 'Prenup Apr 27, 2026: ₱16,000 (Nald) | Wedding Day Mar 14, 2027: ₱40,000',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Prenup + Wedding Coverage ₱65,000, Album ₱7,000, OOTF ₱8,000. 3 Photographers. Full Coverage, Prenup Shoot, Onsite Photo (Same Day Edit), Prenup Slideshow, USB Flashdrive.',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Video Guestbook (Cheers and Clips by Mementoire Studios)',
    estimated_amount: 22000,
    actual_amount: 21980,
    total_paid: 10990,
    gaile_paid: 10990,
    nald_paid: 0,
    balance: 10990,
    first_payment: 'March 1, 2026',
    next_payment: 'March 7, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Classic Package: 2.5x2.5m wooden video guestbook, 2x3 selfie mirror, themed decor, unlimited recordings (3 hrs), highlight reel, full compilation cut, all raw videos.',
  },
  {
    category: 'Styling',
    supplier_name: 'Ceremony - DBC Alvarez',
    estimated_amount: 65000,
    actual_amount: 58500,
    total_paid: 5000,
    gaile_paid: 5000,
    nald_paid: 0,
    balance: 53500,
    first_payment: 'May 18, 2025',
    next_payment: 'March 14, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Ceremony styling and entourage flowers. 10% off, no OOTF, free carpet, bridal car bouquet, loose petals.',
  },
  {
    category: 'Styling',
    supplier_name: 'Chairs - Forrent',
    estimated_amount: 40000,
    actual_amount: 25000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 25000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: 'Ceremony: 100 Rustic/White Wooden Folding Chairs. Reception VIPs: 26 French Margareth Country Chairs. White/Brown Crossback Resin Chair free. Add ₱500 delivery. Confirm chair plan with AE Gee.',
  },
  {
    category: 'Photographer',
    supplier_name: 'Film Photographer: Film8',
    estimated_amount: 50000,
    actual_amount: 33000,
    total_paid: 5000,
    gaile_paid: 5000,
    nald_paid: 0,
    balance: 28000,
    first_payment: 'August 3, 2025',
    next_payment: 'March 14, 2027',
    payment_notes: 'Pay remaining balance. ₱28,000 original + OOTF TBD (est. ₱5,000)',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Wedding Package ₱28,000 + OOTF ₱4,000. 1 Photographer, 1 Assistant, 6 rolls of film (scan & develop), online drive.',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Solemnizing Officer (Rev. Christopher Sablay)',
    estimated_amount: 30000,
    actual_amount: 27000,
    total_paid: 13500,
    gaile_paid: 6750,
    nald_paid: 6750,
    balance: 13500,
    first_payment: 'February 4, 2026',
    next_payment: 'March 14, 2027',
    payment_notes: 'Pay remaining balance',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Contract in Facebook Messenger.',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Paperbean Lane',
    estimated_amount: 40000,
    actual_amount: 39000,
    total_paid: 14150,
    gaile_paid: 7075,
    nald_paid: 7075,
    balance: 24850,
    first_payment: 'December 5, 2025',
    next_payment: 'TBD (40%) / TBD (30%)',
    payment_notes: 'Jan 31, 2026 (30%): ₱10,650/2 = ₱5,325 each | TBD (40%): ₱14,200/2 = ₱7,100 each | TBD (30%): ₱10,650/2 = ₱5,325 each',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Discovery call 12/21/2025. Inclusions: Wedding Branding + 35 Printed Invitations (with mobile version), Wedding Website, Custom Cartoon Animation, Linen Welcome Signage, Digital Save the Date, Creative Consultancy Lock In, Table Numbers (20 pcs die cut).',
  },
  {
    category: 'HMUA Bride',
    supplier_name: 'Prenup MUA: Kate Abalos',
    estimated_amount: 10000,
    actual_amount: 10000,
    total_paid: 10000,
    gaile_paid: 2000,
    nald_paid: 8000,
    balance: 0,
    first_payment: 'March 10, 2026',
    next_payment: '',
    payment_notes: 'Fully paid April 27, 2026',
    status: 'Fully Paid',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Cocktail Hour',
    supplier_name: 'Photo Gallery Display by Dakila Creations',
    estimated_amount: 15000,
    actual_amount: 15000,
    total_paid: 2000,
    gaile_paid: 2000,
    nald_paid: 0,
    balance: 13000,
    first_payment: 'March 1, 2027',
    next_payment: 'February 28, 2027 / March 14, 2027',
    payment_notes: 'Feb 28, 2027: ₱6,500 (50% of remaining) | Mar 14, 2027: ₱6,500',
    status: 'Booked DP Paid',
    contract_sent: 'Yes',
    remarks: 'Dahlia Display: 9 pcs 18×24" on 8×6 ft metal frame, 3 pcs 5R on glass frame, 6 hours display (2–8pm). Free floral decor, spotlight, and OOTF.',
  },
  {
    category: 'Entourage Outfit',
    supplier_name: "Divisoria - Papa & Tito Dindin's Barong, Mama & Tita Marie's Gowns",
    estimated_amount: 20000,
    actual_amount: 20000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 20000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Entourage Outfit',
    supplier_name: "Divisoria - Mark's Barong, Gianne, Mommy, Woona and Soju's Gowns",
    estimated_amount: 20000,
    actual_amount: 20000,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 20000,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
  {
    category: 'Wedding Needs',
    supplier_name: 'Crew Meals',
    estimated_amount: 0,
    actual_amount: 0,
    total_paid: 0,
    gaile_paid: 0,
    nald_paid: 0,
    balance: 0,
    first_payment: '',
    next_payment: '',
    payment_notes: '',
    status: 'Deciding',
    contract_sent: '',
    remarks: '',
  },
];

module.exports = records;
